version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    environment:
      - ENV=LOCAL
      - SECRET_KEY=${SECRET_KEY}
    build: .
    command: >
      bash -c "python /code/crt_portal/manage.py migrate &&
      python /code/crt_portal/manage.py collectstatic --noinput &&
      python /code/crt_portal/manage.py compress &&
      python /code/crt_portal/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: